# Generated by Django 3.1.2 on 2021-04-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_no', models.DecimalField(decimal_places=0, max_digits=4)),
                ('name', models.CharField(max_length=100)),
                ('generation', models.DecimalField(decimal_places=0, max_digits=2)),
                ('status', models.DecimalField(decimal_places=0, max_digits=4)),
                ('species', models.CharField(max_length=30)),
                ('no_type', models.DecimalField(decimal_places=0, max_digits=2)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_point', models.DecimalField(decimal_places=0, max_digits=5)),
                ('hp', models.DecimalField(decimal_places=0, max_digits=4)),
                ('attack', models.DecimalField(decimal_places=0, max_digits=4)),
                ('defense', models.DecimalField(decimal_places=0, max_digits=4)),
                ('sp_attack', models.DecimalField(decimal_places=0, max_digits=4)),
                ('sp_defense', models.DecimalField(decimal_places=0, max_digits=4)),
                ('speed', models.DecimalField(decimal_places=0, max_digits=4)),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_1', to='pokedex.type')),
                ('type_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_2', to='pokedex.type')),
            ],
        ),
    ]
